const PORT = process.env.PORT || 5000;
const MONGO_URI = process.env.MONGO_URI;
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
const FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID;
const FIRBASE_CLIENT_EMAIL = process.env.FIRBASE_CLIENT_EMAIL;
const FIREBAESE_PRIVATE_KEY = process.env.FIREBAESE_PRIVATE_KEY;

module.exports = {
  PORT,
  MONGO_URI,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  FIREBASE_PROJECT_ID,
  FIRBASE_CLIENT_EMAIL,
  FIREBAESE_PRIVATE_KEY,
};
